version: 0.1

phases:
  install:
    commands:
      - go get github.com/Masterminds/glide
  pre_build:
    commands:
      - glide install
      - mkdir -p $GOPATH/src/github/stk132/tsg
      - mv * $GOPATH/src/github/stk132/tsg/.
  build:
    commands:
      - cd $GOPATH/src/github/stk132/tsg && pwd && go build
  post_build:
    commands:
      - env
      - ls -al vendor
